### ISSUE TITLE
File or directory not found  can you please help me The one who would solve my query i will give 50$ via paypal so  with your solution leave ur paypal details

### ISSUE THREAD

**Issue by yashmodi17** [ncorbuk/Python-Ransomware#12]
Traceback (most recent call last):
  File "Ransomware.py", line 250, in <module>
![Screenshot (24)](https://user-images.githubusercontent.com/63386752/125156739-b09ddb00-e184-11eb-9ebb-62d9eef0e2b7.png)

    main()
  File "Ransomware.py", line 232, in main
    rw.encrypt_fernet_key()
  File "Ransomware.py", line 84, in encrypt_fernet_key
    with open(f'{self.sysRoot}Desktop/EMAIL_ME.txt', 'wb') as fa:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AdminDesktop/EMAIL_ME.txt'

**Comment by yashmodi17** [comment]
Help me clear all my issues
