### ISSUE TITLE
decryptingfile

### ISSUE THREAD

**Issue by FeelsBadMan1** [ncorbuk/Python-Ransomware#8]
Hello, i tried the ranspmware on my own pc with a specific path but if i try to rn the decrypting file it giv eout this issure:
```
C:\Users\Administrator\Desktop\Python-Ransomware-master>C:\Users\Administrator\Desktop\Python-Ransomware-master\Decrypt_fernet_key.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Python-Ransomware-master\Decrypt_fernet_key.py", line 6, in <module>
    with open('EMAIL_ME.txt', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'EMAIL_ME.txt'

C:\Users\Administrator\Desktop\Python-Ransomware-master>
```

The EMAIL_ME file is created on the desktop so im not sure what to do.

**Comment by anthonyzutter** [comment]
You have to put the file in the same directory or change the code so it will open the file in the Desktop

**Comment by yashmodi17** [comment]
> You have to put the file in the same directory or change the code so it will open the file in the Desktop

Its not working bro can you please help me?

**Comment by yashmodi17** [comment]
Traceback (most recent call last):
  File "Ransomware.py", line 250, in <module>
    main()
  File "Ransomware.py", line 232, in main
    rw.encrypt_fernet_key()
  File "Ransomware.py", line 84, in encrypt_fernet_key
    with open(f'{self.sysRoot}Desktop/EMAIL_ME.txt', 'wb') as fa:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AdminDesktop/EMAIL_ME.txt'
![Screenshot (24)](https://user-images.githubusercontent.com/63386752/125156681-60bf1400-e184-11eb-93b7-7b89d915a365.png)

**Comment by FeelsBadMan1** [comment]
This error means that yo dont got a EMAIL_ME.txt onto your desktop

**Comment by yashmodi17** [comment]
> This error means that yo dont got a EMAIL_ME.txt onto your desktop

No i got a EMAIL_TXT file but nothing is written in it after running ransomware

**Comment by dv8081** [comment]
make a file or directory on desktop with same name EMAIL_ME.txt and try again it works.

**Comment by Potato-git13** [comment]
> > This error means that yo dont got a EMAIL_ME.txt onto your desktop
> 
> No i got a EMAIL_TXT file but nothing is written in it after running ransomware

The path would need to be C:\Users\Admin\Desktop/EMAIL_ME.txt
